version: "3"
services:
  db:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.dbdev
    volumes:
      - all_jobs_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  dev:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.dev
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8001
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - db
  bot_manager:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.dev
    command: python manage.py bot_manager
    stdin_open: true
    tty: true
    user: "${UID}:${GID}"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - dev
volumes:
  all_jobs_pg_data:
  redis_data:
