version: "3"
services:
  db:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.dbdev
    volumes:
      - all_jobs_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  dev:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.dev
    stdin_open: true
    tty: true
    command: bash -c "python manage.py makemigrations && python manage.py migrate --noinput &&
      gunicorn all_jobs.wsgi:application --bind 0.0.0.0:8001 --workers=5"
    volumes:
      - all_jobs_admin_data:/app
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - db
  bot_manager:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.dev
    command: bash -c "python manage.py bot_manager"
    stdin_open: true
    tty: true
    volumes:
      - all_jobs_admin_data:/app
    env_file:
      - .env
    depends_on:
      - db
      - dev
    networks:
      - admin_vacancy_network
volumes:
  all_jobs_pg_data:
  all_jobs_admin_data:
networks:
  admin_vacancy_network:
    external: true

