# Generated by Django 5.0.6 on 2024-06-11 11:41

import wagtail.blocks
import wagtail.fields
import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesettings',
            name='text',
            field=wagtailmarkdown.fields.MarkdownField(default='{{ tags }}\n\n**{{ title }}**\n{% for grade in grades %} {{ grade }} {% endfor %}\n\n**Требования к кандидату:**\n{% for item in requirements %}\n{{ item }}\n{% endfor %}\n\n**Обязанности кандидата:**\n{% for item in responsibilities %}\n{{ item }}\n{% endfor %}', help_text='Эта настройка отвечает за то, как будет выглядеть сообщение в канале телеграмма для всех вакансий. Это шаблон!<br/>Здесь работает шаблонизатор jinja2.<br/>Для того, чтобы сделать цикл по элементам:<br/>{% for item in [название переменной] %}<br/>{{ item }}<br/>{% endfor %}<br/>Для того, чтобы сделать условие:<br/>{% if [название переменной] %}<br/>[какие либо действия, будь то вывод переменной или цикл]<br/>{% endif %}<br/>{{ title }} - Заголовок вакансии<br/>{{ specialization }} - Специализация вакансии<br/>{{ stack }} - Стэк вакансии<br/>{{ requirements }} - Требования к кандидату<br/>{{ responsibilities }} - Обязанности кандидата<br/>{{ cost }} - Рейт вакансии<br>{{ location }} - Локация<br>{{ load }} - Загруженность<br>{{ tags }} - Тэги. Будут выводиться в формате тг, то есть с #<br>{{ grades }} - Грейд вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=wagtail.fields.StreamField([('requirements_item', wagtail.blocks.CharBlock(label='Элемент требования'))], blank=True, null=True, verbose_name='Требования к кандидату'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=wagtail.fields.StreamField([('responsibilities_item', wagtail.blocks.CharBlock(label='Элемент обязанности'))], blank=True, null=True, verbose_name='Обязанности кандидата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='stack',
            field=wagtail.fields.StreamField([('stack_item', wagtail.blocks.CharBlock(label='Элемент стэка'))], blank=True, null=True, verbose_name='Стэк'),
        ),
    ]
