# Generated by Django 5.0.6 on 2024-06-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Обработка с помощью ИИ не удалась'), (0, 'Обработка с помощью ИИ'), (1, 'Модерация'), (2, 'Готов к отправке'), (3, 'Отправлен'), (4, 'Найден исполнитель'), (5, 'В исполнении'), (6, 'В архиве')], default=0),
        ),
    ]
