# Generated by Django 5.0.6 on 2024-05-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={},
        ),
        migrations.AlterField(
            model_name='worker',
            name='about_worker',
            field=models.TextField(blank=True, max_length=1000, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='certificates',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Сертификаты'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='databases_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Базы данных'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='education',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='example_of_work',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Пример работ'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='other_technologies_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Другие технологии'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='programming_languages_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Опыт работы с языками'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='skills_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='software_development_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Средства разработки ПО'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='technologies_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Технологии'),
        ),
    ]
