# Generated by Django 5.0.6 on 2024-05-31 15:40

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_alter_worker_options_alter_worker_about_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='citizenship',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Гражданство'),
        ),
    ]
