# Generated by Django 5.0.6 on 2024-06-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_workexperience_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='process_status',
            field=models.IntegerField(choices=[(-1, 'Обработка с помощью ИИ не удалась'), (0, 'Обработка с помощью ИИ'), (1, 'Модерация'), (2, 'Загружен'), (3, 'В архиве')], default=0),
        ),
    ]
