# Generated by Django 5.0.6 on 2024-06-25 11:49

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_worker_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_contact',
            field=wagtail.fields.StreamField([('contact', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Тип контакта')), ('value', wagtail.blocks.CharBlock(label='Значение'))], label='Элемент контакта'))], blank=True, null=True, verbose_name='Контакты сотрудника'),
        ),
    ]
