# Generated by Django 5.0.6 on 2024-07-04 11:46

import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workexperience_technologies_alter_vacancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Обработка с помощью ИИ не удалась'), (0, 'Ожидает одобрения'), (1, 'Обработка с помощью ИИ'), (2, 'Модерация'), (3, 'Готов к публикации'), (4, 'Опубликован'), (5, 'Найден исполнитель'), (6, 'В работе'), (7, 'В архиве')], default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='grade',
            field=wagtail.fields.StreamField([('grade', wagtail.snippets.blocks.SnippetChooserBlock('core.Grade', label='Grade'))], blank=True, null=True, verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='process_status',
            field=models.IntegerField(choices=[(-1, 'Обработка с помощью ИИ не удалась'), (0, 'Обработка с помощью ИИ'), (1, 'Модерация'), (2, 'Загружен'), (3, 'В архиве')], default=0, verbose_name='Process status'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='specialization',
            field=wagtail.fields.StreamField([('specialization', wagtail.snippets.blocks.SnippetChooserBlock('core.Specialization', label='Specialization'))], blank=True, null=True, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Никнейм TG'),
        ),
    ]
