# Generated by Django 5.0.6 on 2024-06-08 15:56

import django.db.models.deletion
import django_countries.fields
import modelcluster.fields
import taggit.managers
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_stepsinboard_remove_worker_skills_text_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', wagtail.fields.RichTextField(help_text='Эта настройка отвечает за то, как будет выглядеть сообщение в канале телеграмма для всех вакансий. Это шаблон!\\<br/>$title - Заголовок вакансии<br/>$requirements - Требования к кандидату<br/>$responsibilities - Обязанности кандидата<br/>$cost - Рейт вакансии<br>$location - Локация<br>$load - Загруженность<br>$tags - Тэги. Будут выводиться в формате тг, то есть с #<br>$grade - Грейд вакансии', max_length=2056)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название вакансии')),
                ('requirements', models.TextField(blank=True, max_length=2056, null=True, verbose_name='Требования к кандидату')),
                ('responsibilities', models.TextField(blank=True, max_length=2056, null=True, verbose_name='Обязанности кандидата')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Рейт вакансии')),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Локация вакансии')),
                ('load', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загрузка вакансии')),
                ('status', models.IntegerField(choices=[(0, 'Модерация'), (1, 'Отправлен')], default=0)),
                ('full_vacancy_text_from_tg_chat', models.TextField(blank=True, verbose_name='Полный текст скопированной из тг вакансии')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Грейд', to='core.grade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='core.vacancy')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.VacancyTags', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
