# Generated by Django 5.0.6 on 2024-07-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vacancy_status_alter_worker_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='process_status',
            field=models.IntegerField(choices=[(-1, 'Обработка с помощью ИИ не удалась'), (0, 'Обработка с помощью ИИ'), (1, 'Модерация'), (2, 'Ожидает вакансии'), (3, 'Подали на запрос'), (4, 'Отказ после собеса'), (5, 'Отказ по резюме'), (6, 'Позвали на собес'), (7, 'Ожидаем ОС'), (8, 'Согласован выход'), (9, 'Не активен'), (10, 'Работает на проекте'), (11, 'В архиве')], default=0, verbose_name='Process status'),
        ),
    ]
