# Generated by Django 5.0.6 on 2024-06-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_messagesettings_vacancy_vacancytags_vacancy_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, help_text='; = новая строка', max_length=2056, null=True, verbose_name='Требования к кандидату'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='; = новая строка', max_length=2056, null=True, verbose_name='Обязанности кандидата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(choices=[(0, 'Обработка с помощью ИИ'), (1, 'Модерация'), (2, 'Готов к отправке'), (3, 'Отправлен')], default=0),
        ),
    ]
