# Generated by Django 5.0.6 on 2024-07-04 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_worker_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Статус кандидата'),
        ),
    ]
