# Generated by Django 5.0.6 on 2024-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Партнер'),
        ),
    ]
