# Generated by Django 5.0.6 on 2024-07-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_demand_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='type',
            field=models.IntegerField(choices=[(-1, '--------------------------'), (0, 'Наемный'), (1, 'Штатный')], default=-1, verbose_name='Тип отношений'),
        ),
    ]
