# Generated by Django 5.0.6 on 2024-07-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_type_alter_worker_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='StepsInBoard',
        ),
    ]
