# Generated by Django 5.0.6 on 2024-07-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_rank_delete_stepsinboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='type',
            field=models.IntegerField(choices=[(-1, '--'), (0, 'Наемный'), (1, 'Штатный'), (2, 'От партнера')], default=-1, verbose_name='Тип отношений'),
        ),
    ]
