# Generated by Django 5.0.6 on 2024-07-20 12:20

from django.db import migrations

currencies = [
    {
        "char_code": "RUB",
        "name": "Rubble",
        "symbol": "₽",
    },
    {
        "char_code": "EUR",
        "name": "Euro",
        "symbol": "€",
    },
    {
        "char_code": "USD",
        "name": "Dollar",
        "symbol": "$",
    },
]


def create_currencies(apps, schema):
    Currency = apps.get_model("core", "CurrencySnippet")
    for currency in currencies:
        Currency(**currency).save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_currencysnippet_worker_salary_and_more'),
    ]

    operations = [
        migrations.RunPython(create_currencies)
    ]
