# Generated by Django 5.0.6 on 2024-07-21 11:57

import django.utils.timezone
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20240720_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_of_application',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of application'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='End work'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Start work'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsibilities',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Responsibilities on project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Role in project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Project team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Project technologies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title project'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Work duration'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.DateField(blank=True, null=True, verbose_name='End work'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.DateField(blank=True, null=True, verbose_name='Start work'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='technologies',
            field=wagtail.fields.StreamField([('technology_item', wagtail.blocks.CharBlock(label='Technology item'))], blank=True, null=True, verbose_name='Project technologies'),
        ),
    ]
