# Generated by Django 5.0.6 on 2024-07-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_project_date_of_application_alter_project_date_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='sales_rate',
        ),
        migrations.AddField(
            model_name='project',
            name='sales_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sales rate'),
        ),
    ]
