# Generated by Django 5.0.6 on 2024-07-21 13:03

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feedback',
            field=wagtail.fields.StreamField([('feedback_item', wagtail.blocks.StructBlock([('type', wagtail.blocks.ChoiceBlock(choices=[(0, 'Negative'), (1, 'Normal'), (2, 'Positive')], label='Type feedback')), ('value', wagtail.blocks.RichTextBlock(label='Feedback text'))], label='Feedback item'))], blank=True, null=True, verbose_name='Feedback'),
        ),
    ]
