# Generated by Django 5.0.6 on 2024-07-21 13:11

import django_countries.fields
import uuid
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='full_vacancy_text_from_tg_chat',
            field=models.TextField(blank=True, verbose_name='Full vacancy text'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='grades',
            field=wagtail.fields.StreamField([('grade', wagtail.snippets.blocks.SnippetChooserBlock('core.Grade'))], blank=True, null=True, verbose_name='Grades'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='load',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Load'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=wagtail.fields.StreamField([('requirements_item', wagtail.blocks.CharBlock(label='Requirements item'))], blank=True, null=True, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=wagtail.fields.StreamField([('responsibilities_item', wagtail.blocks.CharBlock(label='Responsibilities item'))], blank=True, null=True, verbose_name='Responsibilities'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='specialization',
            field=wagtail.fields.StreamField([('specialization', wagtail.snippets.blocks.SnippetChooserBlock('core.Specialization'))], blank=True, null=True, verbose_name='Specializations'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='stack',
            field=wagtail.fields.StreamField([('stack_item', wagtail.blocks.CharBlock(label='Stack item'))], blank=True, null=True, verbose_name='Stacks'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID vacancy'),
        ),
    ]
