# Generated by Django 5.0.6 on 2024-07-21 13:44

import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_duration_demand_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='workers',
            field=wagtail.fields.StreamField([('worker', wagtail.blocks.StructBlock([('worker', wagtail.snippets.blocks.SnippetChooserBlock('core.Worker')), ('role', wagtail.blocks.CharBlock(label='Role in project')), ('sales_rate', wagtail.blocks.StreamBlock([('cost_item', wagtail.blocks.StructBlock([('size', wagtail.blocks.IntegerBlock(label='Cost size')), ('currency', wagtail.snippets.blocks.SnippetChooserBlock('core.CurrencySnippet', label='Cost currency'))], label='Cost item'))], label='Sales rate', max_num=1))], label='Worker info'))], blank=True, null=True, verbose_name='Работник'),
        ),
    ]
