# Generated by Django 5.0.6 on 2024-07-21 14:35

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_demand_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_of_application',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='project',
            name='demand',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.demand'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start work'),
        ),
        migrations.AlterField(
            model_name='project',
            name='worker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.worker', verbose_name='Worker for project'),
        ),
    ]
