# Generated by Django 5.0.6 on 2024-07-21 15:55

import django.db.models.deletion
import django_countries.fields
import uuid
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_demand_workers_remove_project_date_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagesettings',
            options={'verbose_name': 'Message template'},
        ),
        migrations.RemoveField(
            model_name='demand',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='status',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='status_date',
        ),
        migrations.AddField(
            model_name='demand',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Project deadline'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='stack',
            field=wagtail.fields.StreamField([('stack_item', wagtail.blocks.CharBlock(label='Stack item'))], blank=True, null=True, verbose_name='Stack'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(choices=[(-1, 'AI processing failed'), (0, 'Awaiting approval'), (1, 'AI Processing'), (2, 'Moderation'), (3, 'Ready to publish'), (4, 'Published'), (5, 'Worker found'), (6, 'In progress'), (7, 'In archive')], default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='certificates',
            field=wagtail.fields.StreamField([('certificate_item', wagtail.blocks.CharBlock(label='Certificate item'))], blank=True, null=True, verbose_name='Certificates'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='citizenship',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, verbose_name='UUID worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='databases',
            field=wagtail.fields.StreamField([('database_item', wagtail.blocks.CharBlock(label='Database item'))], blank=True, null=True, verbose_name='Databases'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='education',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='employer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employer'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='employer_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employer contacts'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='english_grade',
            field=wagtail.fields.StreamField([('language', wagtail.blocks.StructBlock([('language', wagtail.blocks.CharBlock(label='Language item')), ('grade', wagtail.blocks.CharBlock(label='Language grade'))], label='Language'))], blank=True, null=True, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='example_of_work',
            field=wagtail.fields.StreamField([('example_of_work_item', wagtail.blocks.URLBlock(label='Work example item'))], blank=True, null=True, verbose_name='Example of work'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='experience',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Years of experience'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='grade',
            field=wagtail.fields.StreamField([('grade', wagtail.snippets.blocks.SnippetChooserBlock('core.Grade', label='Grade'))], blank=True, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('type', wagtail.blocks.CharBlock(label='Link type')), ('link', wagtail.blocks.URLBlock(label='Link value'))], label='Link item'))], blank=True, null=True, verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='other_technologies',
            field=wagtail.fields.StreamField([('other_technology_item', wagtail.blocks.CharBlock(label='Other technology item'))], blank=True, null=True, verbose_name='Other technologies'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='process_status',
            field=models.IntegerField(choices=[(-1, 'AI processing failed'), (0, 'AI Processing'), (1, 'Moderation'), (2, 'Waiting for vacancies'), (3, 'Submitted to request'), (4, 'Refusal after social security'), (5, 'Resume refusal'), (6, 'Called for an interview'), (7, 'Waiting for feedback'), (8, 'Output agreed'), (9, 'Not active'), (10, 'Working on the project'), (11, 'Archived')], default=0, verbose_name='Process status'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='programming_languages',
            field=wagtail.fields.StreamField([('language_item', wagtail.blocks.CharBlock(label='Programming language'))], blank=True, null=True, verbose_name='Programming languages'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=wagtail.fields.StreamField([('cost_item', wagtail.blocks.StructBlock([('size', wagtail.blocks.IntegerBlock(label='Cost size')), ('currency', wagtail.snippets.blocks.SnippetChooserBlock('core.CurrencySnippet', label='Cost currency'))], label='Cost item'))], blank=True, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='skills',
            field=wagtail.fields.StreamField([('skill_item', wagtail.blocks.CharBlock(label='Skill item'))], blank=True, null=True, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='software_development',
            field=wagtail.fields.StreamField([('software_development_item', wagtail.blocks.CharBlock(label='Software development item'))], blank=True, null=True, verbose_name='Software developments'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='specialization',
            field=wagtail.fields.StreamField([('specialization', wagtail.snippets.blocks.SnippetChooserBlock('core.Specialization', label='Specialization'))], blank=True, null=True, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='stack',
            field=wagtail.fields.StreamField([('stack_item', wagtail.blocks.CharBlock(label='Stack item'))], blank=True, null=True, verbose_name='Stack'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='technologies',
            field=wagtail.fields.StreamField([('technology_item', wagtail.blocks.CharBlock(label='Technology item'))], blank=True, null=True, verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='type',
            field=models.IntegerField(choices=[(-1, '--'), (0, 'Employed'), (1, 'Standard'), (2, 'From Affiliate')], default=-1, verbose_name='Relationship type'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_contact',
            field=wagtail.fields.StreamField([('contact', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Contact type')), ('value', wagtail.blocks.CharBlock(label='Contact value'))], label='Contact item'))], blank=True, null=True, verbose_name='Contacts'),
        ),
    ]
