# Generated by Django 5.0.6 on 2024-08-07 12:18

import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesettings',
            name='text',
            field=wagtailmarkdown.fields.MarkdownField(default='{{ tags }}\n\n**{{ title }}**\n{% for grade in grades %} {{ grade }} {% endfor %}\n\n**Требования к кандидату:**\n{% for item in requirements %}\n{{ item }}\n{% endfor %}\n\n**Обязанности кандидата:**\n{% for item in responsibilities %}\n{{ item }}\n{% endfor %}', help_text='Эта настройка отвечает за то, как будет выглядеть сообщение в канале телеграмма для всех вакансий. Это шаблон!<br/>Здесь работает шаблонизатор jinja2.<br/>Для того, чтобы сделать цикл по элементам:<br/>{% for item in [название переменной] %}<br/>{{ item }}<br/>{% endfor %}<br/>Для того, чтобы сделать условие:<br/>{% if [название переменной] %}<br/>[какие либо действия, будь то вывод переменной или цикл]<br/>{% endif %}<br/>{{ title }} - Заголовок вакансии<br/>{{ specialization }} - Специализация вакансии<br/>{{ stack }} - Стэк вакансии<br/>{{ requirements }} - Требования к кандидату<br/>{{ responsibilities }} - Обязанности кандидата<br/>{{ cost }} - Рейт вакансии<br>{{ salary }} - ЗП вакансии в формате [число][символ валюты]. Пример - 5000 $<br>{{ location }} - Локация<br>{{ load }} - Загруженность<br>{{ tags }} - Тэги. Будут выводиться в формате тг, то есть с #<br>{{ grades }} - Грейд вакансии'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='type',
            field=models.IntegerField(choices=[(-1, '--'), (0, 'Employee'), (1, 'Standard'), (2, 'From Affiliate')], default=-1, verbose_name='Relationship type'),
        ),
    ]
