# Generated by Django 5.0.6 on 2024-08-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_messagesettings_text_alter_worker_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
