# Generated by Django 5.0.6 on 2024-08-25 14:19

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_demand_customer_vacancy_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='deadline',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Project deadline'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='vacancy',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='core.vacancy'),
        ),
    ]
