# Generated by Django 5.0.6 on 2024-08-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_demand_deadline_vacancy_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C')], default=0, verbose_name='Type vacancy'),
        ),
    ]
