# Generated by Django 5.0.6 on 2024-09-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
