# Generated by Django 5.0.6 on 2024-09-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_vacancy_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
    ]
