# Generated by Django 5.0.6 on 2024-09-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_project_role_remove_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='project',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
