# Generated by Django 5.1.1 on 2024-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_project_demand_remove_project_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C')], default=1, verbose_name='Type vacancy'),
        ),
    ]
