# Generated by Django 5.1.1 on 2024-09-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20240907_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='uuid',
        ),
    ]
