# Generated by Django 5.1.1 on 2024-10-10 09:41

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_vacancy_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_ids', wagtail.fields.StreamField([('chat_id', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 128})}, null=True, verbose_name='Chats')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
