# Generated by Django 5.1.1 on 2024-10-10 09:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_chatids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatids',
            name='chat_ids',
        ),
        migrations.AddField(
            model_name='chatids',
            name='chats',
            field=wagtail.fields.StreamField([('chat', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Chat name', 'max_length': 256}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Chat id', 'max_length': 128}), 2: ('wagtail.blocks.StructBlock', [[('chat_name', 0), ('chat_id', 1)]], {'label': 'Chat'})}, null=True, verbose_name='Chats'),
        ),
    ]
