# Generated by Django 5.1.1 on 2024-10-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0045_chatids_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatids',
            options={'verbose_name': 'Chat for mailing', 'verbose_name_plural': 'Chats for mailing'},
        ),
        migrations.AddField(
            model_name='worker',
            name='input_method',
            field=models.IntegerField(choices=[(0, 'Habr'), (1, 'Head Hunter'), (2, 'Manual')], default=2,
                                      verbose_name='Worker input method'),
        ),
    ]
