# Generated by Django 5.1.1 on 2024-10-10 11:37

from django.db import migrations


def add_input_method(apps, schema):
    Worker = apps.get_model("core", "Worker")
    for worker in Worker.objects.all():
        worker.input_method = 1
        worker.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_chatids_options_worker_input_method'),
    ]

    operations = [
        migrations.RunPython(add_input_method)
    ]
