# Generated by Django 5.1.1 on 2024-10-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_worker_input_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='unique_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='input_method',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'Habr')], default=0, verbose_name='Worker input method'),
        ),
    ]
