# Generated by Django 5.1.1 on 2024-10-18 15:15

from django.db import migrations

from core.choices.worker import WorkerInputMethod


def add_input_method(apps, schema):
    Worker = apps.get_model("core", "Worker")
    for worker in Worker.objects.all():
        worker.input_method = WorkerInputMethod.MANUAL
        worker.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0049_worker_unique_id_alter_worker_input_method'),
    ]

    operations = [
        migrations.RunPython(add_input_method)
    ]
