# Generated by Django 5.1.1 on 2025-02-17 15:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20241018_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='ai_comment',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='AI comment for CV'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='links',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Link type'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Link value'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('value', 1)]], {'label': 'Link item'})}, null=True, verbose_name='Links'),
        ),
    ]
