# Generated by Django 5.1.1 on 2025-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_worker_ai_comment_alter_worker_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='ai_comment',
            field=models.TextField(blank=True, null=True, verbose_name='AI comment for CV'),
        ),
    ]
