# Generated by Django 5.0.12 on 2025-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_worker_ai_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='ai_comment_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
