# Generated by Django 5.0.12 on 2025-03-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_worker_ai_comment_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Education'),
        ),
    ]
