FROM node:16.18.0-alpine

WORKDIR /app

COPY ./package*.json .
COPY ./yarn.lock .

RUN yarn install && mkdir node_modules/.cache && chmod -R 777 node_modules/.cache && \
    mkdir .npm && chmod -R 777 .npm

COPY  . .