# syntax=docker/dockerfile:1

FROM python:3.10.8 as final

RUN pip install nltk

# Создаем папку для данных NLTK
RUN mkdir -p /usr/local/nltk_data

# Загружаем нужные модули
RUN python -m nltk.downloader -d /usr/local/nltk_data punkt averaged_perceptron_tagger stopwords

# Указываем NLTK, где искать данные
ENV NLTK_DATA=/usr/local/nltk_data

RUN addgroup --gid 1001 --system app && \
  adduser --no-create-home --shell /bin/false --disabled-password --uid 1001 --system --group app

EXPOSE 8001

ENV PYTHONUNBUFFERED=1 \
    PORT=8001

RUN apt-get update && \
  apt-get install -y build-essential libpq-dev gettext ffmpeg
RUN apt-get --no-install-recommends install libreoffice -y
RUN apt-get install -y libreoffice-java-common
RUN rm -rf /var/lib/apt/lists/*

RUN pip install "gunicorn==20.0.4"

COPY requirements.txt /
RUN pip install -r /requirements.txt

WORKDIR /app

RUN chown -R app:app /app && pip install --upgrade pip

COPY . .

RUN python manage.py collectstatic --noinput --clear
RUN python manage.py compilemessages -l ru

# Создайте директорию для медиафайлов, если она не существует
RUN mkdir -p /app/media && chown -R app:app /app/media