# syntax=docker/dockerfile:1

FROM python:3.10.8 as final

RUN useradd wagtail

EXPOSE 8001

ENV PYTHONUNBUFFERED=1 \
    PORT=8001

RUN apt-get update && \
  apt-get install -y build-essential libpq-dev gettext ffmpeg
RUN rm -rf /var/lib/apt/lists/*

RUN pip install "gunicorn==20.0.4"

COPY requirements.txt /
RUN pip install -r /requirements.txt

WORKDIR /app

RUN chown wagtail:wagtail /app

COPY --chown=wagtail:wagtail . .

USER wagtail

RUN python manage.py collectstatic --noinput --clear

CMD set -xe; python manage.py makemigrations; python manage.py migrate --noinput; gunicorn all_jobs.wsgi:application -b :8001
