# Generated by Django 5.0.6 on 2024-08-07 14:54

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models

DEFAULT_PROMPTS = [
    {
        "label": "AI Correction",
        "description": "Correct grammar and spelling",
        "prompt": """
You are assisting a user in writing content for their website.
The user has provided some text (following the colon).
Return the provided text but with corrected grammar, spelling and punctuation.
Do not add additional punctuation, quotation marks or change any words:""",
        "method": "REPLACE",
    },
    {
        "label": "AI Completion",
        "description": "Get help writing more content based on what you've written",
        "prompt": """
You are assisting a user in writing content for their website.
The user has provided some initial text (following the colon).
Assist the user in writing the remaining content:""",
        "method": "APPEND",
    },
]


def add_default_prompts(apss, schema):
    Prompt = apss.get_model("parser_ai", "Prompt")
    prompts = [{"type": "prompt", "value": {"label": item["label"],
                                            "method": item["method"],
                                            "prompt": item["prompt"],
                                            "description": item["description"]}} for item in DEFAULT_PROMPTS]
    Prompt(prompts=prompts).save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompts', wagtail.fields.StreamField([('prompt', wagtail.blocks.StructBlock(
                    [('label', wagtail.blocks.CharBlock(max_length=64, verbose_name='Prompt label')),
                     ('prompt', wagtail.blocks.TextBlock(max_length=1024, verbose_name='Prompt')),
                     ('description', wagtail.blocks.TextBlock(max_length=1024, verbose_name='Prompt description')),
                     ('method', wagtail.blocks.ChoiceBlock(choices=[('REPLACE', 'Replace'), ('APPEND', 'Append')]))]))],
                                                       blank=True, null=True, verbose_name='Prompts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_default_prompts)
    ]
